### ISSUE TITLE
No stripe_customer() returned

### ISSUE THREAD

**Issue by tabulapicta** [kreativ-anders/kirby-memberkit#1]
Hi there - firstly, great work on this memberkit!

I've got an issue where your `'customer' => kirby()->user()->stripe_customer()` return nothing which leads to an error in the Stripe logs "resource_missing - customer".

Thoughts on why this is?

The Stripe customer id is not being stored in the relevent customer's index.php file when the user is created. In the documentation, the automatic "create stripe useres" hook states: _"Creates a stripe customer and store the stripe customer id (stripe_customer) and the root subscription tier name (tier) in the Kirby user information."_ This doesn't seem to be occuring in my iteration. I'm using the Add-on Usekit.

The document states _"Check out the Kirby Add-on Userkit to allow self-registration and updates to kirby users."_ Not clear to me what this instruction means, but perhaps I'm missing a step here?

Thanks!

*Update:

I also checked the plugin's hooks.php and can see there is the following hook (the first Stripe customer creation step works, but this second update Kirby user hook does not seem to work (an no error is thrown either):
```
try {

      // UPDATE KIRBY USER - ROOT TIER (INDEX=0)
      kirby()->user($user->email())->update([
        'stripe_customer' => $customer->id,
        'tier' => option('kreativ-anders.memberkit.tiers')[0]['name']
      ]);

    } catch (Exception $e) {
    
      // LOG ERROR SOMEWHERE !!!
      throw new Exception('Could not update kirby user!');
    }
```

**Comment by parislettau** [comment]
I can't explain why, but this piece of code in the register.php controller that is part of the kirby-userkit prevented the hook.php code quoted above in the kirby-memberkit plugin from executing properly:

```
 // SUCCESSFUL
      if (empty($alert) === true) {

        // LOGIN USER
        if($user and $user->login($data['password'])) {
          go();
        }  

        $data = [];
      }
```

**Comment by Manuel-Steinberg** [comment]
First of all: I am sorry!

I did not receive a single notification that new issues have been created, so I was totally unaware until I received a notification from Stripe regarding some changes on the API. 🙄😒

**Comment by Manuel-Steinberg** [comment]
### Step by Step

> The Stripe customer id is not being stored in the relevent customer's index.php file when the user is created.

This will never be the case since this information will be stored in the customer´s **user.txt**. 

> Thoughts on why this is? 

Remove the *user.login:after* hook in your config: 
(Just had the same issue and removing was my solution. Surprisingly it happens not all the time. 😵)

```php
'hooks' => [
    'user.login:after' => function ($user, $session) {
      $user->update([
        'lastLogin' => date("m.d.Y")
      ]);
    }
  ],
```

Even though hooks are great, they can cause a lot of trouble, especially when those hooks access the same object. (For instance the user object by *user.login:after* and *user.create:after* hook.) There is already an issue on https://github.com/getkirby/kirby/issues/2828.

> The document states "Check out the Kirby Add-on Userkit to allow self-registration and updates to Kirby users." Not clear to me what this instruction means, but perhaps I'm missing a step here?

No steps missed. This means the Memberkit Plug-In does not provide the logic for user registration itself (that´s what Userkit does). What this Plug-In does is to listen to *user.create:after* hook to create a Stripe user automatically and write the information back to the user.txt. 

```txt
Stripe-customer: cus_K6V*******
----
Tier: Premium
----
Stripe-subscription: sub_K6V********
----
Stripe-status: active
```

So you can write your own logic for user registration/creation and the Plug-In should work as well.

> Removing that (which prevent auto-login) has solved the entire issue. The auto-login can be moved to execute after the hook.

Yes, either this way or removing the hook *user.login:after* at all. (I plan to remove from Userkit anyway 🙈)

So I hope my late response did not prevent progress on your side! Are there any open issues?

P.S. feel free to also write on the [Kirby´s forum for this Plug-In](https://forum.getkirby.com/t/kirby-memberkit-a-subscription-based-membership-plug-in-powered-by-stripe/21500). At least there I have no notification issues.
